---

# Variables setup
- name: Include os-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Install the Docker Engine
- include: docker_engine.yml
  when: not skip_engine

# Setup the Docker Swarm Cluster
- include: swarm_cluster.yml
  when: not skip_swarm
